version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install -U pip
      # TODO: once we do not depend on datalad-next@main, this can go
      - pip install -r requirements-devel.txt
      - pip install -e .